# Generated by Django 4.1 on 2022-08-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('appearance', models.CharField(max_length=200)),
                ('smell', models.CharField(max_length=200)),
                ('taste', models.CharField(max_length=200)),
                ('marriage', models.CharField(max_length=200)),
                ('ibu', models.FloatField()),
            ],
        ),
    ]
